# Generated by Django 6.1 on 2026-08-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone / WhatsApp number')),
                ('target_destination', models.CharField(blank=True, choices=[('canada', 'Canada'), ('uk', 'UK'), ('ireland', 'Ireland'), ('australia', 'Australia'), ('spain', 'Spain'), ('malta', 'Malta'), ('dubai', 'Dubai'), ('france', 'France')], max_length=20)),
                ('highest_qualification', models.CharField(blank=True, choices=[('bsc_first_2_1', "Bachelor's Degree (1st Class / 2:1)"), ('bsc_2_2_third', "Bachelor's Degree (2:2 / 3rd Class)"), ('hnd', 'HND'), ('masters', "Master's"), ('secondary', "O'Level / Secondary")], max_length=20)),
                ('proof_of_funds', models.CharField(blank=True, choices=[('15m_25m', '₦15M – ₦25M'), ('25m_40m', '₦25M – ₦40M'), ('40m_plus', '₦40M+'), ('need_guidance', 'Still planning / Need financial guidance')], max_length=20)),
                ('has_funds_evidence', models.CharField(blank=True, max_length=10, verbose_name='Has evidence of stated funds now, or within 30 days')),
                ('study_timeline', models.CharField(blank=True, choices=[('next_intake', 'Next Available Intake'), ('within_6_months', 'Within 6 Months'), ('within_12_months', 'Within 12 Months'), ('just_exploring', 'Just Exploring')], max_length=20)),
                ('service_needed', models.CharField(blank=True, choices=[('admissions', 'University Admissions'), ('visa_support', 'Visa Application Support'), ('family_relocation', 'Family Relocation'), ('unsure', 'Unsure / Need Consultation')], max_length=20)),
                ('agreed_terms', models.BooleanField(default=False)),
                ('agreed_privacy', models.BooleanField(default=False)),
                ('consent_contact', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('get_started', 'Get Started form'), ('book_consultation', 'Book Consultation (paid)')], default='get_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
