# Generated by Django 6.1 on 2026-08-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='proof_of_funds',
        ),
        migrations.AlterField(
            model_name='lead',
            name='has_funds_evidence',
            field=models.CharField(blank=True, max_length=20, verbose_name='Has evidence of stated funds now, or within 30 days'),
        ),
    ]
