# Generated by Django 6.1 on 2026-08-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_proof_of_funds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='proof_of_funds',
            field=models.CharField(blank=True, choices=[('15m_25m', '₦15M – ₦25M'), ('25m_40m', '₦25M – ₦40M'), ('40m_plus', '₦40M+'), ('need_guidance', 'Still planning / Need financial guidance')], max_length=20),
        ),
    ]
