# Generated by Django 6.1 on 2026-09-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_payment_add_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='has_funds_evidence',
            field=models.CharField(blank=True, max_length=20, verbose_name='Has evidence of stated funds now, or within 30 days'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('get_started', 'Get Started form')], default='get_started', max_length=20),
        ),
    ]
