# Generated by Django 6.1 on 2026-09-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_has_funds_evidence_alter_lead_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='agreed_privacy',
        ),
    ]
